enchmnts = {
    1  : "Aqua Affinity",
    2  : "Bane of Arthropods",
    3  : "Blast Protection",
    4  : "Channeling",
    5  : "Curse of Binding",
    6  : "Curse of Vanishing",
    7  : "Depth Strider",
    8  : "Efficiency",
    9  : "Feather Falling",
    10 : "Fire Aspect",
    11 : "Fire Protection",
    12 : "Flame",
    13 : "Fortune",
    14 : "Frost Walker",
    15 : "Impaling",
    16 : "Infinity",
    17 : "Knockback",
    18 : "Looting",
    19 : "Loyalty",
    20 : "Luck of the Sea",
    21 : "Lure",
    22 : "Mending",
    23 : "Multishot",
    24 : "Piercing",
    25 : "Power",
    26 : "Projectile Protection",
    27 : "Protection",
    28 : "Punch",
    29 : "Quick Charge",
    30 : "Respiration",
    31 : "Riptide",
    32 : "Sharpness",
    33 : "Silk Touch",
    34 : "Smite",
    35 : "Soul Speed",
    36 : "Sweeping Edge",
    37 : "Thorns",
    38 : "Unbreaking",
}

recipients = {
    1:"@p",
    2:"@r",
    3:"@a",
    4:"@e",
}